---
prelim_clone: https://github.com/karltayoto-tip/sysad2-12021.git
username: karltayoto-tip
ftp_user: ftp_user
ftp_pass: $6$3i.kgSfN2m.uQ$GA/tmEw6c0MqRfE2DFJpD.msaGdz8wUwv/iuhlbz23L/31wBUMs6y.oJ61ZxSOkfRy5IaLAf4jg/hnROzpKI1
nagadminpass: $6$cxs4204fy5C$z0lf7XbPo06tOEivogqlKPlmkjpmWj36DIfh10DtodeSyd21yu7TrC6lIDe4xY6o9IBLncU97SWw6mtOIDUeo1
nagadmin: nagadmin
nagpass: $6$obQgDis8C4$Fd88JHcoEUuTNnDWZYJXLh8QLEqQsUONKuRSD3.B038DkG7uJW8K9yrZkb3TxDaMl77Q5Un3sxEwmKYsk7dW3/
