---
# tasks file for roles/opensuse/install-vsftpd
- name: install vsftpd service
  become: yes
  zypper:
    name: vsftpd
    state: present
    update_cache: yes

- name: change state of firewalld
  become: yes
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: start vsftpd
  become: yes
  service:
    name: vsftpd
    state: started
    enabled: yes
